let S={view:'home',filter:'Todos',favorites:new Set(),cart:[],location:'27 de Febrero',mode:'Delivery',detailQty:1,guide:{step:0,mission:'mude',space:'2',owned:[],budget:250000}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],byId=id=>PRODUCTS.find(p=>p.id===id),fmt=n=>'RD$'+Number(n).toLocaleString('en-US',{maximumFractionDigits:2});
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1400)}
function imageHTML(p){return `<img src="${p.img}" alt="${p.name}" onerror="this.outerHTML=FALLBACKS['${p.type}']">`}
function updateCartBadge(){let c=S.cart.reduce((a,b)=>a+b.qty,0),e=$('#cartCount');e.textContent=c;e.classList.remove('bump');void e.offsetWidth;e.classList.add('bump')}
function setNav(n){$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.nav===n))}
function catButton(title,sub){return `<button class="cat" data-category="${title}"><span class="caticon">${title==='Hogar'?ICONS.home:title==='Electrodomésticos'?ICONS.grid:ICONS.spark}</span><b>${title}</b><small>${sub}</small></button>`}
function card(p){return `<article class="card" data-product="${p.id}"><button class="fav ${S.favorites.has(p.id)?'active':''}" data-fav="${p.id}">${ICONS.heart}</button><div class="photo">${imageHTML(p)}</div><div class="body"><div class="brand">${p.brand}</div><h3>${p.name}</h3><div class="pricebar"><strong>${fmt(p.price)}</strong><button class="add" data-add="${p.id}">Agregar</button></div></div></article>`}
function home(){let popular=['fridge','washer','ac','pillow','cutlery'].map(byId),hogar=PRODUCTS.filter(p=>p.dept==='Hogar').slice(0,5);return `<section class="view"><div class="hero"><div class="kicker">Compra por necesidad</div><h1>Encuentra lo que necesitas sin perderte.</h1><p>Compra por categoría como siempre o dile a Plaza Lama qué estás resolviendo y arma una selección más rápido.</p><div class="hero-actions"><button class="primary" data-category="Hogar">${ICONS.home} Comprar Hogar</button><button class="secondary" data-guide>${ICONS.spark} Ayúdame a elegir</button></div></div><div class="section"><div class="section-head"><div><h2>Explora</h2><p>Accesos rápidos</p></div></div><div class="categories">${catButton('Hogar','Dormitorio y cocina')}${catButton('Electrodomésticos','Neveras, lavado y clima')}${catButton('Neveras','Refrigeración')}${catButton('Clima','Aires')}${catButton('Lavado','Lavadoras')}</div></div><div class="section"><div class="section-head"><div><h2>Popular ahora</h2><p>Productos para resolver la casa</p></div><button class="linkbtn" data-category="Electrodomésticos">Ver todo</button></div><div class="scroll">${popular.map(card).join('')}</div></div><div class="section"><div class="plan"><div class="kicker">Resuelve con Plaza Lama</div><h3>Me mudé. ¿Qué compro primero?</h3><p>Cuéntanos tamaño, presupuesto y lo que ya tienes. Te mostramos una base y la ajustas sin empezar de nuevo.</p><button class="primary" data-guide>${ICONS.spark} Crear mi selección</button></div></div><div class="section"><div class="section-head"><div><h2>Para el hogar</h2><p>Básicos que completan el espacio</p></div><button class="linkbtn" data-category="Hogar">Ver Hogar</button></div><div class="scroll">${hogar.map(card).join('')}</div></div></section>`}
function category(title){let list=title==='Hogar'?PRODUCTS.filter(p=>p.dept==='Hogar'):title==='Electrodomésticos'?PRODUCTS.filter(p=>p.dept==='Electrodomésticos'):PRODUCTS.filter(p=>p.cat===title);let chips=['Todos',...new Set(list.map(p=>p.cat))];let shown=S.filter==='Todos'?list:list.filter(p=>p.cat===S.filter);return `<section class="view"><div class="screenhead"><button class="back" data-home>${ICONS.back}</button><div><h1>${title}</h1><p>${shown.length} productos</p></div></div><div class="chips">${chips.map(c=>`<button class="chip ${S.filter===c?'active':''}" data-filter="${c}" data-screen="${title}">${c}</button>`).join('')}</div><div class="grid">${shown.map(card).join('')}</div></section>`}
function favorites(){let list=PRODUCTS.filter(p=>S.favorites.has(p.id));return `<section class="view"><div class="screenhead"><button class="back" data-home>${ICONS.back}</button><div><h1>Guardados</h1><p>${list.length?list.length+' productos':'Guarda productos para verlos después'}</p></div></div>${list.length?`<div class="grid">${list.map(card).join('')}</div>`:`<div class="plan"><h3>Aún no has guardado nada.</h3><p>Toca el corazón de cualquier producto para guardarlo aquí.</p><button class="secondary" data-home>Explorar productos</button></div>`}</section>`}
function categoriesView(){return `<section class="view"><div class="screenhead"><button class="back" data-home>${ICONS.back}</button><div><h1>Categorías</h1><p>Compra por lo que necesitas</p></div></div><div class="grid" style="grid-template-columns:1fr 1fr">${catButton('Hogar','Dormitorio y cocina')}${catButton('Electrodomésticos','Neveras, lavado y clima')}${catButton('Neveras','Refrigeración')}${catButton('Clima','Aires')}${catButton('Lavado','Lavadoras')}${catButton('TV','Televisores')}</div></section>`}